MODE: OPENBRIDGE
ENABLED: true
IP: ""
PORT: 62044
NETWORK_ID: 1
PASSPHRASE: passw0rd
TARGET_IP: ""
TARGET_PORT: 62044
USE_ACL: true
SUB_ACL: DENY:1
TGID_ACL: DENY:0-82,92-199,800-899,9990-9999,730999
RELAX_CHECKS: true
ENHANCED_OBP: true
PROTO_VER: 5
