MODE: MASTER
ENABLED: false
REPEAT: true
MAX_PEERS: 2
EXPORT_AMBE: false
IP: ""
PORT: 62030
PASSPHRASE: passw0rd
GROUP_HANGTIME: 5
USE_ACL: true
REG_ACL: DENY:1
SUB_ACL: DENY:1
TGID_TS1_ACL: PERMIT:ALL
TGID_TS2_ACL: PERMIT:ALL
DEFAULT_UA_TIMER: 60
SINGLE_MODE: false
VOICE_IDENT: false
TS1_STATIC: ""
TS2_STATIC: ""
DEFAULT_REFLECTOR: 0
ANNOUNCEMENT_LANGUAGE: es_ES
GENERATOR: 0
ALLOW_UNREG_ID: false
PROXY_CONTROL: false
OVERRIDE_IDENT_TG: ""
