#!/usr/bin/env bash
# Seed /opt/adn-docker/.env + deploy.conf (production, no toolkit on host).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DOCKER="$(cd "$SCRIPT_DIR/.." && pwd)"
GITHUB_RAW="${GITHUB_RAW:-https://raw.githubusercontent.com/ce5rpy/ADN-Install/master}"

SERVER_ROOT="${ADN_SERVER_ROOT:-/opt/adn-docker}"
ENV_FILE="$SERVER_ROOT/.env"
DEPLOY_CONF="$SERVER_ROOT/deploy.conf"
STATE="$SERVER_ROOT/state"

force=0
[[ "${1:-}" == "--force" ]] && force=1

if [[ -f "$ENV_FILE" || -f "$DEPLOY_CONF" ]] && [[ "$force" -ne 1 ]]; then
  echo "Already exists (use --force to overwrite):" >&2
  [[ -f "$ENV_FILE" ]] && echo "  $ENV_FILE" >&2
  [[ -f "$DEPLOY_CONF" ]] && echo "  $DEPLOY_CONF" >&2
  exit 1
fi

if [[ "$force" -eq 1 ]]; then
  echo "NOTE: if MariaDB was already initialized, new passwords in .env will NOT apply" >&2
  echo "      to the existing volume. Reset with:" >&2
  echo "        docker compose -f $SERVER_ROOT/docker-compose.yml --env-file $ENV_FILE down" >&2
  echo "        docker volume rm adn_mariadb_data" >&2
  echo "      then re-run install." >&2
fi

if docker volume inspect adn_mariadb_data >/dev/null 2>&1 && [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: MariaDB volume adn_mariadb_data exists but $ENV_FILE is missing." >&2
  echo "  Remove the volume to create fresh credentials:" >&2
  echo "    docker volume rm adn_mariadb_data" >&2
  exit 1
fi

if [[ -f "$SCRIPT_DIR/materialize-standalone.sh" ]]; then
  bash "$SCRIPT_DIR/materialize-standalone.sh"
else
  _mat="$(mktemp)"
  curl -fsSL "$GITHUB_RAW/install-docker/scripts/materialize-standalone.sh" -o "$_mat"
  bash "$_mat"
  rm -f "$_mat"
fi

TRAEFIK_HOST_NAMES="${TRAEFIK_HOST_NAMES:-_}"
TRAEFIK_ACME_EMAIL="${TRAEFIK_ACME_EMAIL:-admin@example.com}"
HBP_PASSPHRASE="passw0rd"

adn_rand_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    tr -dc 'a-f0-9' </dev/urandom | head -c 32
  fi
}

db_pass="$(adn_rand_hex)"
root_pass="$(adn_rand_hex)"
if [[ -f "$ENV_FILE" ]]; then
  _old_db="$(grep -E '^MYSQL_DB_PASSWORD=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true)"
  _old_root="$(grep -E '^MYSQL_ROOT_PASSWORD=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true)"
  if docker volume inspect adn_mariadb_data >/dev/null 2>&1; then
    [[ -n "$_old_db" ]] && db_pass="$_old_db"
    [[ -n "$_old_root" ]] && root_pass="$_old_root"
    echo "  bootstrap: keeping MariaDB passwords (volume adn_mariadb_data exists)"
  fi
fi
registry="${DOCKER_REGISTRY:-docker.io/ce5rpy}"
registry="${registry%/}"
export DOCKER_REGISTRY="$registry"

# shellcheck source=install-docker/lib/compose-env.sh
if [[ -f "$INSTALL_DOCKER/lib/compose-env.sh" ]]; then
  source "$INSTALL_DOCKER/lib/compose-env.sh"
  adn_docker_resolve_release_vars
else
  _env_lib="$(mktemp)"
  _tag_lib="$(mktemp)"
  curl -fsSL "$GITHUB_RAW/install-docker/lib/compose-env.sh" -o "$_env_lib"
  curl -fsSL "$GITHUB_RAW/install-docker/lib/docker-tag.sh" -o "$_tag_lib"
  # shellcheck source=/dev/null
  source "$_tag_lib"
  # shellcheck source=/dev/null
  source "$_env_lib"
  adn_docker_resolve_release_vars
  rm -f "$_env_lib" "$_tag_lib"
fi

# Always materialize image refs for .env (resolve may skip export if registry unset in env)
adn_docker_export_image_refs "$registry"

cat >"$ENV_FILE" <<EOF
# Generated by bootstrap-standalone.sh — registry pull
ADN_DEPLOY_MODE=registry
ADN_SERVER_ROOT=${SERVER_ROOT}
ADN_DOCKER_STATE=${STATE}

DOCKER_REGISTRY=${registry}
ADN_RELEASE_CHANNEL=${ADN_RELEASE_CHANNEL:-auto}
DOCKER_TAG_SERVER=${DOCKER_TAG_SERVER}
DOCKER_TAG_MONITOR=${DOCKER_TAG_MONITOR}
DOCKER_TAG_DAPRS=${DOCKER_TAG_DAPRS}
DOCKER_TAG_DEPLOY_CLI=${DOCKER_TAG_DEPLOY_CLI}
ADN_IMAGE_SERVER=${ADN_IMAGE_SERVER:-${registry}/adn-server:${DOCKER_TAG_SERVER}}
ADN_IMAGE_MONITOR=${ADN_IMAGE_MONITOR:-${registry}/adn-monitor:${DOCKER_TAG_MONITOR}}
ADN_IMAGE_DAPRS=${ADN_IMAGE_DAPRS:-${registry}/daprs:${DOCKER_TAG_DAPRS}}
ADN_IMAGE_DEPLOY_CLI=${ADN_IMAGE_DEPLOY_CLI:-${registry}/adn-deploy-cli:${DOCKER_TAG_DEPLOY_CLI}}

MYSQL_DB_NAME=hbmon
MYSQL_DB_USER=self_service_user
MYSQL_DB_PASSWORD=${db_pass}
MYSQL_ROOT_PASSWORD=${root_pass}

TRAEFIK_HTTP_PORT=80
TRAEFIK_HTTPS_PORT=443
TRAEFIK_CONFIG_DIR=./state/traefik
MONITOR_APP_PORT=8080
ADN_SERVER_PORT=62031
HBP_PASSPHRASE=passw0rd

GIT_URL_PEER=https://github.com/ce5rpy/ADN-DMR-Peer-Server.git
GIT_URL_MONITOR=https://github.com/ce5rpy/ADN-Monitor.git
GIT_BRANCH_PEER=${GIT_BRANCH_PEER}
GIT_BRANCH_MONITOR=${GIT_BRANCH_MONITOR}
EOF
chmod 600 "$ENV_FILE"

cat >"$DEPLOY_CONF" <<EOF
# ADN Docker runtime — registry (/opt/adn-docker only; CLI from container image)
ADN_DEPLOY_DOCKER=1
ADN_DEPLOY_MODE=registry
ADN_SERVER_ROOT="${SERVER_ROOT}"
ADN_DEPLOY_CONF="${DEPLOY_CONF}"
ADN_DOCKER_ROOT="${SERVER_ROOT}"
ADN_DOCKER_STATE="${STATE}"
ADN_DOCKER_COMPOSE_FILE="${SERVER_ROOT}/docker-compose.yml"
ADN_DOCKER_ENV_FILE="${ENV_FILE}"
ADN_DOCKER_PROFILE="full"

ADN_ROOT="${STATE}"
ADN_DMR_SERVER_PATH="${STATE}/peer"
ADN_MONITOR_PATH="${STATE}/monitor"
ADN_DEPLOY_SKIP_OS_PACKAGES=1

TRAEFIK_HOST_NAMES="${TRAEFIK_HOST_NAMES}"
WEB_SSL="0"
TRAEFIK_ACME_EMAIL="${TRAEFIK_ACME_EMAIL}"
TRAEFIK_PRIMARY_DOMAIN=""

MONITOR_APP_PORT="8080"
MONITOR_APP_UPSTREAM="adn-monitor"
HBP_PASSPHRASE="passw0rd"
ADN_SERVER_ID=""
ADN_DASHTITLE=""

MYSQL_DB_NAME="hbmon"
MYSQL_DB_USER="self_service_user"
EOF
chmod 644 "$DEPLOY_CONF"

echo "Created:"
echo "  $ENV_FILE"
echo "  $DEPLOY_CONF"
echo "  $SERVER_ROOT/docker-compose.yml"
echo "  $STATE/traefik/   (HTTP :80; WEB_SSL=0)"
